### ISSUE TITLE
Thank you for sharing your work!

### ISSUE THREAD

**Issue by esutton** [meedan/i18n-translate-json#1]
I generated 16 language translations for my react-native app in about 20 seconds!

A great tool!

Would you mind if I copy your project and try to make a new project to translate Qt linguist TS files?

Qt translate files an XML file format.

http://doc.qt.io/qt-5/qtlinguist-hellotr-example.html
```
<!DOCTYPE TS><TS>
<context>
    <name>QPushButton</name>
    <message>
        <source>Hello world!</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
```

**Comment by caiosba** [comment]
Thanks for that!

You can go ahead and fork it (instead of copying) :)

**Comment by esutton** [comment]
Forked.  Thanks!

**Comment by caiosba** [comment]
Great!
