### ISSUE TITLE
Cannot translate HTML input

### ISSUE THREAD

**Issue by Steffion** [meedan/i18n-translate-json#3]
You're blocking HTML translation on purpose?
Why is this? Some of my translations contain HTML tags.

https://github.com/meedan/i18n-translate-json/blob/fdaeabba4ea88a378be98f2e124e6ae1afa8e679/translate.js#L20

**Comment by Steffion** [comment]
That’d be great.

**Comment by ThaDaVos** [comment]
Is it already possible to translate html input? I'm running into the same issue as my translations file contains labels and html texts

**Comment by Steffion** [comment]
@ThaDaVos I made a fix in my fork just now. Check it here: https://github.com/Steffion/i18n-translate-json/tree/feature/include-html-flag
I will request a PR.

**Comment by caiosba** [comment]
Thanks, merged and released new version.
